FROM python:3.12-slim AS builder

ENV VIRTUAL_ENV=/opt/venv \
    PATH="/opt/venv/bin:$PATH"

RUN apt-get update && apt-get install -y curl build-essential && \
    python -m venv $VIRTUAL_ENV && \
    curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s /root/.local/bin/poetry /usr/local/bin/poetry

WORKDIR /vma

COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root --only main

COPY . .
RUN poetry build


FROM python:3.12-slim AS prod

WORKDIR /vma

COPY --from=builder /vma/dist/*.whl ./

RUN pip install *.whl && rm *.whl
RUN pip install gunicorn

ENTRYPOINT [ \
    "gunicorn", \
    "vma.web.web:app", \
    "-k", \
    "uvicorn.workers.UvicornWorker", \
    "--forwarded-allow-ips=*", \
    "-w", \
    "4", \
    "-b", \
    "0.0.0.0:80", \
    "--timeout", \
    "60", \
    "--graceful-timeout", \
    "30", \
    "--keep-alive", \
    "5" \
]
